name: Deploy to Hugging Face Spaces
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        run: |
          python scripts/update_readme.py
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Update README
        run: |
          python scripts/update_readme.py
          git add README.md
          git commit -m "README metadata"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://ericbotti:$HF_TOKEN@huggingface.co/spaces/ericbotti/chameleon main